apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  namespace: airflow
spec:
  storageClassName: airflow-dags-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/airflow-volume/dags"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-worker-pv
  namespace: airflow
spec:
  storageClassName: airflow-logs-worker-pv
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/airflow-volume/logs-airflow/worker"
